messages:
  invalidDateFormat: "createdAfter parameter must be in YYYY-MM-DD format."
  missingParameter: "%s parameter is missing."
  errorGitHubRepoServiceParsingData: "Error processing repository data: {}"
  errorGitHubRepoServiceParsingDate: "Error parsing updated_at date: {}"